/**
 * Curated emoji set for the inbox composer picker.
 *
 * Deliberately hand-rolled instead of pulling in emoji-mart / the full
 * Unicode CLDR dataset: those ship 1–2 MB of JSON into the client bundle
 * for a picker that agents use to drop a 👍 into a reply. This list covers
 * the emoji that actually show up in customer chats, and every glyph here
 * renders on WhatsApp (Unicode 12 and below, no ZWJ sequences beyond the
 * common family/profession ones we skip entirely).
 *
 * `keywords` drive the search box and are English-only — the category
 * tabs are the localized affordance for non-English agents.
 */

export interface EmojiEntry {
  /** The emoji glyph itself — inserted verbatim into the composer. */
  char: string;
  /** Lowercase, space-separated search terms (English). */
  keywords: string;
}

export type EmojiCategoryId =
  | 'smileys'
  | 'gestures'
  | 'people'
  | 'nature'
  | 'food'
  | 'activity'
  | 'travel'
  | 'objects'
  | 'symbols';

export interface EmojiCategory {
  id: EmojiCategoryId;
  /** Glyph used as the category tab icon. */
  icon: string;
  emojis: readonly EmojiEntry[];
}

const e = (char: string, keywords: string): EmojiEntry => ({ char, keywords });

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  {
    id: 'smileys',
    icon: '😀',
    emojis: [
      e('😀', 'grin smile happy'),
      e('😃', 'smile happy joy'),
      e('😄', 'smile happy laugh'),
      e('😁', 'grin beam happy'),
      e('😆', 'laugh satisfied happy'),
      e('😅', 'sweat laugh relief'),
      e('🤣', 'rofl laugh lol'),
      e('😂', 'joy laugh tears lol'),
      e('🙂', 'slight smile'),
      e('🙃', 'upside down silly'),
      e('😉', 'wink flirt'),
      e('😊', 'blush smile happy'),
      e('😇', 'innocent angel halo'),
      e('🥰', 'love hearts adore'),
      e('😍', 'heart eyes love'),
      e('🤩', 'star struck wow amazing'),
      e('😘', 'kiss love'),
      e('😗', 'kiss'),
      e('😚', 'kiss closed eyes'),
      e('😙', 'kiss smile'),
      e('😋', 'yum tasty delicious'),
      e('😛', 'tongue playful'),
      e('😜', 'wink tongue joke'),
      e('🤪', 'zany crazy silly'),
      e('😝', 'tongue squint'),
      e('🤑', 'money mouth rich'),
      e('🤗', 'hug hugging'),
      e('🤭', 'oops giggle hand over mouth'),
      e('🤫', 'shush quiet secret'),
      e('🤔', 'thinking hmm think'),
      e('🤐', 'zipper mouth silence'),
      e('🤨', 'raised eyebrow suspicious'),
      e('😐', 'neutral meh'),
      e('😑', 'expressionless blank'),
      e('😶', 'no mouth speechless'),
      e('😏', 'smirk sly'),
      e('😒', 'unamused annoyed'),
      e('🙄', 'eye roll whatever'),
      e('😬', 'grimace awkward'),
      e('🤥', 'lying pinocchio'),
      e('😌', 'relieved calm'),
      e('😔', 'pensive sad'),
      e('😪', 'sleepy tired'),
      e('🤤', 'drooling'),
      e('😴', 'sleeping zzz'),
      e('😷', 'mask sick'),
      e('🤒', 'sick fever thermometer'),
      e('🤕', 'hurt injured bandage'),
      e('🤢', 'nauseated sick gross'),
      e('🤮', 'vomit sick'),
      e('🥵', 'hot heat sweating'),
      e('🥶', 'cold freezing'),
      e('😵', 'dizzy shocked'),
      e('🤯', 'mind blown exploding head'),
      e('🤠', 'cowboy'),
      e('🥳', 'party celebrate birthday'),
      e('😎', 'sunglasses cool'),
      e('🤓', 'nerd geek glasses'),
      e('🧐', 'monocle inspect'),
      e('😕', 'confused unsure'),
      e('😟', 'worried'),
      e('🙁', 'frown sad'),
      e('😮', 'open mouth surprised wow'),
      e('😯', 'hushed surprised'),
      e('😲', 'astonished shocked'),
      e('😳', 'flushed embarrassed'),
      e('🥺', 'pleading please puppy eyes'),
      e('😦', 'frowning open mouth'),
      e('😧', 'anguished'),
      e('😨', 'fearful scared'),
      e('😰', 'anxious sweat nervous'),
      e('😥', 'sad relieved disappointed'),
      e('😢', 'cry sad tear'),
      e('😭', 'sobbing cry loud'),
      e('😱', 'scream fear shocked'),
      e('😖', 'confounded'),
      e('😣', 'persevere struggle'),
      e('😞', 'disappointed sad'),
      e('😓', 'downcast sweat'),
      e('😩', 'weary tired'),
      e('😫', 'tired exhausted'),
      e('🥱', 'yawn bored'),
      e('😤', 'triumph steam determined'),
      e('😡', 'angry mad rage'),
      e('😠', 'angry annoyed'),
      e('🤬', 'cursing swearing angry'),
      e('😈', 'devil mischievous'),
      e('💀', 'skull dead'),
      e('💩', 'poop'),
      e('🤡', 'clown'),
      e('👻', 'ghost boo'),
      e('👽', 'alien'),
      e('🤖', 'robot bot'),
      e('😺', 'cat smile'),
      e('😻', 'cat heart eyes'),
      e('🙈', 'see no evil monkey'),
      e('🙉', 'hear no evil monkey'),
      e('🙊', 'speak no evil monkey'),
    ],
  },
  {
    id: 'gestures',
    icon: '👍',
    emojis: [
      e('👍', 'thumbs up yes ok good like'),
      e('👎', 'thumbs down no bad dislike'),
      e('👌', 'ok perfect'),
      e('🤌', 'pinched fingers'),
      e('🤏', 'pinch small'),
      e('✌️', 'victory peace'),
      e('🤞', 'fingers crossed luck hope'),
      e('🤟', 'love you'),
      e('🤘', 'rock horns'),
      e('🤙', 'call me shaka'),
      e('👈', 'point left'),
      e('👉', 'point right'),
      e('👆', 'point up'),
      e('👇', 'point down'),
      e('☝️', 'index up one'),
      e('✋', 'hand stop high five'),
      e('🤚', 'raised back of hand'),
      e('🖐️', 'hand fingers splayed'),
      e('🖖', 'vulcan spock'),
      e('👋', 'wave hello hi bye'),
      e('🤝', 'handshake deal agreement'),
      e('🙏', 'pray thanks please'),
      e('✍️', 'writing hand sign'),
      e('👏', 'clap applause bravo'),
      e('🙌', 'raising hands celebration praise'),
      e('👐', 'open hands'),
      e('🤲', 'palms up'),
      e('💪', 'muscle strong flex'),
      e('🦾', 'mechanical arm strong'),
      e('👊', 'fist bump punch'),
      e('✊', 'raised fist'),
      e('🤛', 'left fist bump'),
      e('🤜', 'right fist bump'),
      e('👀', 'eyes look see'),
      e('🧠', 'brain smart'),
      e('👅', 'tongue'),
      e('👄', 'lips mouth'),
      e('💋', 'kiss mark lipstick'),
    ],
  },
  {
    id: 'people',
    icon: '🧑',
    emojis: [
      e('👶', 'baby'),
      e('🧒', 'child kid'),
      e('👦', 'boy'),
      e('👧', 'girl'),
      e('🧑', 'person adult'),
      e('👨', 'man'),
      e('👩', 'woman'),
      e('🧓', 'older person'),
      e('👴', 'old man grandpa'),
      e('👵', 'old woman grandma'),
      e('🧑‍💼', 'office worker professional'),
      e('👨‍💻', 'man technologist developer'),
      e('👩‍💻', 'woman technologist developer'),
      e('🧑‍🔧', 'mechanic technician'),
      e('🧑‍🍳', 'cook chef'),
      e('🧑‍🏫', 'teacher'),
      e('🧑‍⚕️', 'health worker doctor nurse'),
      e('💁', 'tipping hand information'),
      e('🙋', 'raising hand question'),
      e('🙆', 'gesturing ok'),
      e('🙅', 'gesturing no stop'),
      e('🤦', 'facepalm'),
      e('🤷', 'shrug dunno'),
      e('🙇', 'bowing sorry please'),
      e('🕺', 'dancing man'),
      e('💃', 'dancing woman'),
      e('🚶', 'walking'),
      e('🏃', 'running'),
      e('👪', 'family'),
      e('👫', 'couple'),
      e('❤️‍🔥', 'heart on fire passion'),
      e('👑', 'crown king queen'),
      e('🎅', 'santa christmas'),
      e('🦸', 'superhero'),
      e('🧑‍🎓', 'student graduate'),
      e('👮', 'police officer'),
    ],
  },
  {
    id: 'nature',
    icon: '🌿',
    emojis: [
      e('🐶', 'dog puppy'),
      e('🐱', 'cat kitten'),
      e('🐭', 'mouse'),
      e('🐹', 'hamster'),
      e('🐰', 'rabbit bunny'),
      e('🦊', 'fox'),
      e('🐻', 'bear'),
      e('🐼', 'panda'),
      e('🐨', 'koala'),
      e('🐯', 'tiger'),
      e('🦁', 'lion'),
      e('🐮', 'cow'),
      e('🐷', 'pig'),
      e('🐸', 'frog'),
      e('🐵', 'monkey'),
      e('🐔', 'chicken'),
      e('🐧', 'penguin'),
      e('🐦', 'bird'),
      e('🦆', 'duck'),
      e('🦉', 'owl'),
      e('🐝', 'bee honey'),
      e('🦋', 'butterfly'),
      e('🐛', 'bug caterpillar'),
      e('🐢', 'turtle slow'),
      e('🐍', 'snake'),
      e('🐬', 'dolphin'),
      e('🐳', 'whale'),
      e('🐟', 'fish'),
      e('🐙', 'octopus'),
      e('🦄', 'unicorn magic'),
      e('🐴', 'horse'),
      e('🐘', 'elephant'),
      e('🌸', 'cherry blossom flower'),
      e('🌹', 'rose flower love'),
      e('🌻', 'sunflower'),
      e('🌷', 'tulip flower'),
      e('🌺', 'hibiscus flower'),
      e('🌼', 'daisy flower'),
      e('💐', 'bouquet flowers'),
      e('🌱', 'seedling growth'),
      e('🌿', 'herb leaf'),
      e('🍀', 'four leaf clover luck'),
      e('🌳', 'tree'),
      e('🌵', 'cactus'),
      e('🌍', 'earth globe world'),
      e('🌙', 'moon night'),
      e('⭐', 'star'),
      e('🌟', 'glowing star sparkle'),
      e('✨', 'sparkles shine new'),
      e('⚡', 'lightning fast power'),
      e('🔥', 'fire hot lit'),
      e('💧', 'droplet water'),
      e('🌊', 'wave ocean water'),
      e('☀️', 'sun sunny'),
      e('⛅', 'cloud sun weather'),
      e('☁️', 'cloud'),
      e('🌧️', 'rain'),
      e('❄️', 'snowflake cold winter'),
      e('🌈', 'rainbow'),
    ],
  },
  {
    id: 'food',
    icon: '🍔',
    emojis: [
      e('🍏', 'green apple fruit'),
      e('🍎', 'apple fruit'),
      e('🍐', 'pear'),
      e('🍊', 'orange tangerine'),
      e('🍋', 'lemon'),
      e('🍌', 'banana'),
      e('🍉', 'watermelon'),
      e('🍇', 'grapes'),
      e('🍓', 'strawberry'),
      e('🍒', 'cherries'),
      e('🍑', 'peach'),
      e('🥭', 'mango'),
      e('🍍', 'pineapple'),
      e('🥥', 'coconut'),
      e('🥝', 'kiwi'),
      e('🍅', 'tomato'),
      e('🥑', 'avocado'),
      e('🥕', 'carrot'),
      e('🌽', 'corn'),
      e('🌶️', 'chili spicy hot pepper'),
      e('🍞', 'bread'),
      e('🥐', 'croissant'),
      e('🧀', 'cheese'),
      e('🍳', 'egg cooking breakfast'),
      e('🥓', 'bacon'),
      e('🍔', 'burger hamburger'),
      e('🍟', 'fries'),
      e('🍕', 'pizza'),
      e('🌭', 'hot dog'),
      e('🌮', 'taco'),
      e('🌯', 'burrito'),
      e('🥗', 'salad healthy'),
      e('🍜', 'noodles ramen soup'),
      e('🍣', 'sushi'),
      e('🍤', 'shrimp fried'),
      e('🍚', 'rice'),
      e('🍰', 'cake slice dessert'),
      e('🎂', 'birthday cake'),
      e('🧁', 'cupcake'),
      e('🍪', 'cookie'),
      e('🍫', 'chocolate'),
      e('🍬', 'candy sweet'),
      e('🍦', 'ice cream'),
      e('🍩', 'donut'),
      e('☕', 'coffee tea hot drink'),
      e('🍵', 'tea green'),
      e('🥤', 'soda drink cup'),
      e('🧃', 'juice box'),
      e('🍺', 'beer'),
      e('🍻', 'beers cheers'),
      e('🥂', 'clinking glasses cheers celebrate'),
      e('🍷', 'wine'),
      e('🥃', 'whisky'),
      e('🍾', 'champagne celebration'),
      e('🧊', 'ice cube'),
    ],
  },
  {
    id: 'activity',
    icon: '⚽',
    emojis: [
      e('⚽', 'soccer football'),
      e('🏀', 'basketball'),
      e('🏈', 'american football'),
      e('⚾', 'baseball'),
      e('🎾', 'tennis'),
      e('🏐', 'volleyball'),
      e('🏉', 'rugby'),
      e('🎱', 'billiards pool 8ball'),
      e('🏓', 'ping pong table tennis'),
      e('🏸', 'badminton'),
      e('🥊', 'boxing glove'),
      e('🥋', 'martial arts'),
      e('⛳', 'golf'),
      e('🎣', 'fishing'),
      e('🏊', 'swimming'),
      e('🚴', 'cycling bike'),
      e('🏋️', 'weight lifting gym'),
      e('🧘', 'yoga meditation calm'),
      e('🏆', 'trophy win award'),
      e('🥇', 'first place gold medal'),
      e('🥈', 'second place silver'),
      e('🥉', 'third place bronze'),
      e('🎖️', 'medal honor'),
      e('🎯', 'target bullseye goal'),
      e('🎲', 'dice game'),
      e('🎮', 'video game controller'),
      e('🎧', 'headphones music'),
      e('🎵', 'music note'),
      e('🎶', 'music notes'),
      e('🎤', 'microphone sing'),
      e('🎸', 'guitar'),
      e('🎹', 'piano keyboard'),
      e('🥁', 'drum'),
      e('🎬', 'clapper movie film'),
      e('🎨', 'art palette paint'),
      e('🎭', 'theater performing arts'),
      e('🎉', 'party popper celebrate congrats'),
      e('🎊', 'confetti celebrate'),
      e('🎈', 'balloon party'),
      e('🎁', 'gift present'),
      e('🎀', 'ribbon bow'),
      e('🪄', 'magic wand'),
    ],
  },
  {
    id: 'travel',
    icon: '🚗',
    emojis: [
      e('🚗', 'car auto'),
      e('🚕', 'taxi'),
      e('🚙', 'suv car'),
      e('🚌', 'bus'),
      e('🚎', 'trolleybus'),
      e('🏎️', 'racing car fast'),
      e('🚓', 'police car'),
      e('🚑', 'ambulance'),
      e('🚒', 'fire engine'),
      e('🚚', 'delivery truck shipping'),
      e('🚛', 'lorry truck'),
      e('🛵', 'scooter delivery'),
      e('🏍️', 'motorcycle'),
      e('🚲', 'bicycle bike'),
      e('✈️', 'airplane flight travel'),
      e('🛫', 'departure takeoff'),
      e('🛬', 'arrival landing'),
      e('🚀', 'rocket launch fast'),
      e('🛸', 'ufo'),
      e('🚁', 'helicopter'),
      e('⛵', 'sailboat'),
      e('🚢', 'ship cruise'),
      e('🚂', 'train'),
      e('🚇', 'metro subway'),
      e('🗺️', 'map'),
      e('📍', 'pin location here'),
      e('🧭', 'compass direction'),
      e('🏠', 'house home'),
      e('🏡', 'house garden home'),
      e('🏢', 'office building company'),
      e('🏬', 'department store shop'),
      e('🏦', 'bank'),
      e('🏥', 'hospital'),
      e('🏫', 'school'),
      e('🏨', 'hotel'),
      e('🏭', 'factory'),
      e('🗼', 'tower landmark'),
      e('🗽', 'statue of liberty'),
      e('🏝️', 'island beach vacation'),
      e('🏖️', 'beach umbrella holiday'),
      e('⛰️', 'mountain'),
      e('🌋', 'volcano'),
      e('🏕️', 'camping tent'),
      e('🌃', 'night city stars'),
      e('🌇', 'sunset city'),
      e('🎆', 'fireworks'),
    ],
  },
  {
    id: 'objects',
    icon: '💼',
    emojis: [
      e('📱', 'phone mobile smartphone'),
      e('💻', 'laptop computer'),
      e('🖥️', 'desktop computer'),
      e('⌨️', 'keyboard'),
      e('🖨️', 'printer'),
      e('📷', 'camera photo'),
      e('📹', 'video camera'),
      e('🎥', 'movie camera'),
      e('☎️', 'telephone call'),
      e('📞', 'phone receiver call'),
      e('📟', 'pager'),
      e('📠', 'fax'),
      e('🔋', 'battery'),
      e('🔌', 'plug power'),
      e('💡', 'light bulb idea'),
      e('🔦', 'flashlight'),
      e('🕯️', 'candle'),
      e('📺', 'tv television'),
      e('📻', 'radio'),
      e('⏰', 'alarm clock time'),
      e('⏱️', 'stopwatch timer'),
      e('⌛', 'hourglass waiting time'),
      e('📅', 'calendar date'),
      e('📆', 'calendar schedule'),
      e('📌', 'pushpin pin'),
      e('📎', 'paperclip attachment'),
      e('✂️', 'scissors cut'),
      e('📝', 'memo note write'),
      e('✏️', 'pencil write'),
      e('🖊️', 'pen write'),
      e('📖', 'book open read'),
      e('📚', 'books library'),
      e('📰', 'newspaper news'),
      e('📄', 'document page file'),
      e('📊', 'bar chart report stats'),
      e('📈', 'chart up growth increase'),
      e('📉', 'chart down decrease loss'),
      e('📋', 'clipboard list'),
      e('📁', 'folder file'),
      e('🗂️', 'dividers folders'),
      e('🗃️', 'file box archive'),
      e('🗑️', 'trash delete bin'),
      e('📦', 'package box parcel shipping'),
      e('📮', 'postbox mail'),
      e('✉️', 'envelope email mail'),
      e('📧', 'email'),
      e('💼', 'briefcase business work'),
      e('🔑', 'key access'),
      e('🔒', 'lock secure private'),
      e('🔓', 'unlock open'),
      e('🔍', 'search magnifying glass find'),
      e('🔗', 'link url chain'),
      e('💰', 'money bag cash'),
      e('💵', 'dollar cash money'),
      e('💳', 'credit card payment'),
      e('🧾', 'receipt invoice bill'),
      e('🛒', 'shopping cart order'),
      e('🛍️', 'shopping bags purchase'),
      e('🏷️', 'label tag price'),
      e('🎫', 'ticket'),
      e('🔧', 'wrench fix tool'),
      e('🔨', 'hammer build'),
      e('⚙️', 'gear settings config'),
      e('🧰', 'toolbox tools'),
      e('💊', 'pill medicine'),
      e('🩺', 'stethoscope health'),
    ],
  },
  {
    id: 'symbols',
    icon: '❤️',
    emojis: [
      e('❤️', 'red heart love'),
      e('🧡', 'orange heart'),
      e('💛', 'yellow heart'),
      e('💚', 'green heart'),
      e('💙', 'blue heart'),
      e('💜', 'purple heart'),
      e('🖤', 'black heart'),
      e('🤍', 'white heart'),
      e('🤎', 'brown heart'),
      e('💔', 'broken heart'),
      e('💕', 'two hearts love'),
      e('💖', 'sparkling heart'),
      e('💗', 'growing heart'),
      e('💘', 'heart arrow cupid'),
      e('💝', 'heart gift'),
      e('💯', 'hundred perfect score'),
      e('✅', 'check done yes ok complete'),
      e('☑️', 'checkbox checked done'),
      e('✔️', 'check mark done'),
      e('❌', 'cross no wrong cancel'),
      e('❎', 'cross mark button no'),
      e('⭕', 'circle correct'),
      e('❗', 'exclamation important'),
      e('❓', 'question help'),
      e('⚠️', 'warning caution alert'),
      e('🚫', 'prohibited forbidden no'),
      e('🔔', 'bell notification'),
      e('🔕', 'bell off mute'),
      e('📢', 'loudspeaker announcement'),
      e('📣', 'megaphone announce'),
      e('💬', 'speech balloon chat message'),
      e('💭', 'thought balloon'),
      e('🗯️', 'anger bubble'),
      e('👁️‍🗨️', 'eye speech'),
      e('🔝', 'top up'),
      e('🆕', 'new'),
      e('🆗', 'ok button'),
      e('🆓', 'free'),
      e('🔄', 'refresh sync repeat'),
      e('▶️', 'play'),
      e('⏸️', 'pause'),
      e('⏹️', 'stop'),
      e('⏩', 'fast forward'),
      e('⬆️', 'up arrow'),
      e('⬇️', 'down arrow'),
      e('➡️', 'right arrow next'),
      e('⬅️', 'left arrow back'),
      e('🔁', 'repeat loop'),
      e('➕', 'plus add'),
      e('➖', 'minus subtract'),
      e('✖️', 'multiply times'),
      e('➗', 'divide'),
      e('™️', 'trademark'),
      e('©️', 'copyright'),
      e('#️⃣', 'hash number'),
      e('1️⃣', 'one 1'),
      e('2️⃣', 'two 2'),
      e('3️⃣', 'three 3'),
      e('🔴', 'red circle'),
      e('🟠', 'orange circle'),
      e('🟡', 'yellow circle'),
      e('🟢', 'green circle'),
      e('🔵', 'blue circle'),
      e('⚫', 'black circle'),
      e('⚪', 'white circle'),
    ],
  },
];

/** Flat lookup used by the search box. */
export const ALL_EMOJIS: readonly EmojiEntry[] = EMOJI_CATEGORIES.flatMap(
  (c) => c.emojis
);

/**
 * Substring match over glyph + keywords. Kept dumb on purpose: the list is
 * ~500 entries, so filtering on every keystroke costs nothing.
 */
export function searchEmojis(query: string): readonly EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return ALL_EMOJIS;
  return ALL_EMOJIS.filter(
    (entry) => entry.char === q || entry.keywords.includes(q)
  );
}
